import styles from "./page.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className={styles.main}>
        <h1 className={styles.title}>URL Shortener</h1>

        <p className={styles.description}>Acorta tus URLs aquí</p>

        <div className={styles.grid}>
          <form className={styles.card}>
            <input type="text" className={styles.input} placeholder="URL" />
            <button className={styles.button}>Acorta</button>
          </form>
        </div>
      </main>
    </div>
  );
}
